# Generated by Django 5.1.3 on 2024-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Trending', 'Trending'), ('Recent', 'Recent')], max_length=100),
        ),
    ]
